### ISSUE TITLE
Add-Ons with Input Modifiers cannot currently effect boot mode

### ISSUE THREAD

**Issue by arntsonl** [OpenStickCommunity/GP2040-CE#257]
@RobertDaleSmith brought up an interesting point:

add-ons that modify inputs such as GPIO expanders cannot currently change the boot mode.

This is because add-ons are loaded after the boot-mode is checked.

Either move add-on loads to before boot mode, OR have add-ons with early load and add-ons with normal load.

**Comment by arntsonl** [comment]
Fixed with @NickGuyver's code!

**Comment by RobertDaleSmith** [comment]
I tested the latest update with my SNES2USB adapter and the boot options work great now. But it seems the other hotkeys are not. For example changing the d-pad to either left or right analog is still not working with add-ons. Did you run into this as well @NickGuyver ?

**Comment by arntsonl** [comment]
Hmmm sounds like another issue maybe? Could you open a new issue and we'll figure it out :)
